[package]
name = "pdfl"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
lalrpop-util = { version = "0.20", features = ["lexer"] }
wasm-bindgen = "0.2"

[build-dependencies]
lalrpop = "0.22.2"
